version: '3.9'

services:
  backend-dev:
    image: django-movies
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/appuser/app/movies
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - 8000:8000
    stdin_open: true