# Generated by Django 4.2.6 on 2023-10-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_actor_biography_alter_actor_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='recommendedations', to='movies.movie', symmetrical=False),
        ),
    ]
