# Generated by Django 4.2.6 on 2023-10-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
