# Generated by Django 4.2.6 on 2023-10-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='recommendations',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
